spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8b206.p.ssafy.io:3306/wooahan?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: wooahan
    password: penguin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
oauth2:
  google:
    client-id: 
    client-secret: 
    redirect-uri: 
    token-uri: 
    resource-uri: 
  kakao:
    client-id : 
    client-secret : 
    redirect-uri : 
    token-uri :
    resource-uri : 
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  config:
    classpath:
      log4j2.yml

server:
  port: 9090
